sudo: required
dist: trusty
language: node_js
node_js:
- '8.5'
addons:
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
jobs:
  include:
  - stage: test
    before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    script:
    - npm test
    after_script:
    - sh -e /etc/init.d/xvfb stop
  - stage: build, package and push to dockerhub
    env:
    - secure: pucqxRGAlIJ6rvmqXIEBY+flSu7zgySzRVWh7T/64I50ucm2OKDermiLtvQD8/70b9l+0G3RNljnRrBVryOh1ms+soD8lIjdt5bZqipio/z0P6nJrDIf/DeJTtJ1D9mRoH79uvgFedGFT6pRAekjZ/DgUG6eJwz4muEA5wZ3wwXiBD0wCIehUBcXF2CggtY9CEGyJPRMM6Pp4HM7QJiR+LcLaocEUAIxYrlSod7YL6/F2C2IiX6LUBiI2K5SG1a9AC2mh5yNUxaqj9U6kTrDWBqUUuLil5NkICrCmBfIB/NkMxgI/ocFzBHHU2yyim6/hnNK/zvjNSNh6pN/2ZpWWntkrZfbvzEwaOlht4pzksjMvkoS9iA6Wd4Uct39J6VzMGVYd+RfhUVW2HQz/U5dzXsDTj56XOdREdIfrB+JVyxq4yzGxjsNFkZdzIF7ZIQn+DUpWEUqUZ/KWCLktiMmG1+nzfnVOTtOcOpqfxjiwuXfF4C/tg+CU171m5BrXQzk3KQ84dUA7YK6/Te2nrUGkCHVvxkrIKuqHGZUWhmpEa+hMr2PZxtbY847dhLC2evG49M0z4SLj9mNFhS7ol720H7uY0A0RmI/fWAoDAY3pHaxupfM9dDSLQQwCnf1pdrz0dAF38HVQFFgl17PK4ssbU0grA26RdqznEhnM4sYb4Y=
    - secure: KzVvzUDzVG4qlJMZsG0EryK/617ySksqk6Kqirw197C3bGhs8GoeAc0MW123GUSaZmQckk6BjVpgVnmp0HDxUONYuwczlMYCBJDSjDL5ol0ZQpiAgV1MkofgQo5Io86sIaWqBQZnt80DeM9ebYyC7mTVo0uOYJjj04s4KT2Nf4zOLWgsR9tn6fft32eQZwfVLzcEIJVlE2uFjwgnykt0h0nbIm0i9KNviFuUwC+yUogQpQcWTFC/0wg1x0zlVhrM2phs6CC+9oWyHekqpnNTtb5t0QdlTJjr+mG4+5JbXvXuUaZb7TsjN6JPme777Azb0g9EW3HH9BoWunhtf1DbvOXWH0FbcylwsMfbLAF8FeOv+b1o2lcB0+4KxnsGYdAGBJamWDGYfG3KLseB0PeJ1B23mQKw1S4UctJ2ueV8FU+1hd+HX2IL8bhmxyrCmCKNEb1/nQyBSvkl0cg1Xi2tJ0q46/iy6aUGsqS2ynM2XgVJ42VLZHwdgtRES7WQdwTnzcErhc6NTVbsHsi7dY14ioBHedv0Il5EPICMx0SUs9HGVPhm5AmtWLAPwZdcQRaY3DV/hw81ooE5AEHCqaZr0lmjNKQ7TzzuImUkm3KgGyx+k4MjaPOcHs+BJ22dA6xwtOe4ji16xAe1srGlTkZYJPiudLL4WOHPjjfqZz8q1Ow=
    - secure: O+xpNk2sflQ0nfylvTHUCCMfYGACE7YDPUUT8Rsu1lp88zU9FusMVKPxfrn4jRgeOroG0g5toNRKOUw9whtgYXqA7+Z9uJPGZytcd59lS8mLA2/dU8/ZaMqDYQlbztTq+8NLonCqaqFaWwcVGSAOqSJ8xJDxZp8CHb9DVxhp58V6Hhi/bMEvIcYtB++x+H1ATwEQJ7tZfV49yqW+Z2YtMpxFsl0cP33SdoGJvfjrNurAoc11vMm2S4EFgMtXFuUiEXWZodjG6S0180ODtBSVExmG0cP7+dsnw9vMxL3UUhJYK61gC9s73zO1RgZck+6UPgnjnCPXQB94Bt8Z/IjorMZqFGCfQWNkbiFJthYBpAaGYgFQJeuHYttE9u0Fz+9VRFTXWRSNyyspSD1CO+Ha1zaoZLuiGAxr96qqRYn9HCF14UxcwTDvfoOUbiRt+ji4S2PBWf2HUe1vK+DjsDP+PRaYmRAY5z0KjqUwz5Xs9v5dBqZi5WFtr1GKtyFs3lAMVbboSTYIKOCzr8scBVuE9D5m2gRrgXw6D0xJoucdM+bsR9x+T+ZCd8vifSjCPFut+m5X8Oh0U23ocIatg1Cv9x/mifghb/c6w3JjgDopdkgB1DLHL55Hn+l16Jrx6o14lvaVTuqkIZcvm+KXLtCsFrRLYBWhZhjQ1aZ+M2zZuqM=
    - COMMIT=${TRAVIS_COMMIT::8}
    services:
    - docker
    script:
    - npm publish
    - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
    - export REPO=cwr10010docker/shoppinglist-js
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo
      $TRAVIS_BRANCH ; fi`
    - docker build -f Dockerfile -t $REPO:$COMMIT .
    - docker tag $REPO:$COMMIT $REPO:$TAG
    - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
    - docker push $REPO
  - stage: deploy on testing
    addons:
      ssh_known_hosts: cwrose.de
    install: skip
    script: skip
    before_deploy:
      - openssl aes-256-cbc -K $encrypted_2ff5d1c3c112_key -iv $encrypted_2ff5d1c3c112_iv -in $TRAVIS_BUILD_DIR/deploy/deploy_rsa.enc -out /tmp/deploy_rsa -d
      - eval "$(ssh-agent -s)"
      - chmod 600 /tmp/deploy_rsa
      - ssh-add /tmp/deploy_rsa
    deploy:
      provider: script
      skip_cleanup: true
      script: sh $TRAVIS_BUILD_DIR/deploy/do_deploy.sh test
      on:
        branch: master
    after_deploy:
      - ssh-add -d
      - rm  /tmp/deploy_rsa
