sudo: required
dist: trusty
language: node_js
node_js:
  - '8.5'
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
jobs:
  include:
    - stage: test
      before_install:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      before_script:
      - npm install -g @angular/cli
      - npm install
      - ng build
      script: ng test --watch=false --code-coverage
      after_script:
        - sh -e /etc/init.d/xvfb stop
