import { NgModule } from '@angular/core';
import {
  MdGridListModule,
  MdButtonModule,
  MdFormFieldModule,
  MdInputModule,
  MdCardModule,
  MdMenuModule,
  MdIconModule,
  MdChipsModule,
  MdAutocompleteModule,
  MdOptionModule,
  MdListModule,
  MdExpansionModule,
  MdToolbarModule,
  MdSlideToggleModule,
  MdCheckboxModule
} from '@angular/material';

@NgModule({
  imports: [
  MdGridListModule,
  MdButtonModule,
  MdFormFieldModule,
  MdInputModule,
  MdCardModule,
  MdMenuModule,
  MdIconModule,
  MdChipsModule,
  MdAutocompleteModule,
  MdOptionModule,
  MdListModule,
  MdExpansionModule,
  MdToolbarModule,
  MdSlideToggleModule,
  MdCheckboxModule,
  ],
  exports: [
  MdGridListModule,
  MdButtonModule,
  MdFormFieldModule,
  MdInputModule,
  MdCardModule,
  MdMenuModule,
  MdIconModule,
  MdChipsModule,
  MdAutocompleteModule,
  MdOptionModule,
  MdListModule,
  MdExpansionModule,
  MdToolbarModule,
  MdSlideToggleModule,
  MdCheckboxModule,
  ],
})
export class CustomMaterialModule { }
